from tkinter import *
root = Tk()
root.geometry("900x500")
root.option_add("*Font","aerial 14 bold")
lblName = Label(root,text="Enter Name:")
lblName.place(relx=0.05,rely=0.05)
txtName = Entry(root)
txtName.place(relx=0.2,rely=0.06)
lblEmail = Label(root,text="Enter Email:")
lblEmail.place(relx=0.05,rely=0.15)
txtEmail = Entry(root)
txtEmail.place(relx=0.2,rely=0.15)
btnSubmit = Button(root,text="Submit")
btnSubmit.place(relx=0.05,rely=0.25)
root.mainloop()