import numpy as np
# arr = np.array([2,4,5])
# print(arr[0])
# arr = np.array([[1,2,3,8],[7,8,9,8]])
# print(arr)
# print(arr.ndim)
# print(arr.size)
# print(arr.dtype)
# print(arr[0,:]) #first row
# print(arr[:,3])
# arr = np.zeros([2,3])
# arr=np.full((2,3),75)
# arr=np.random.rand(2,3)
arr=np.random.randint(0,5,size=(3,3))
print(arr)
