import numpy as np
# arr = np.array([2,4,5])
# print(arr[0])
# arr = np.array([[1,2,3],[7,8,9]])
# print(arr[1,2])
# print(arr.ndim)
# print(arr.size)
# print(arr.dtype)
#print(arr[0,:]) #first row
# print(arr[:,2])
# arr = np.zeros([2,3])
# arr=np.full((2,3),75)
# arr=np.random.rand(1,3)
arr=np.random.randint(0,5,size=(3,3))
print(arr)
